/** @type {import('tailwindcss').Config} */

module.exports = {
    content: ["./src/**/*.{js,jsx,ts,tsx}"],
    theme: {
      extend: {
        colors: {
          default: {
            50: 'var(--color-default-50)',
            100: 'var(--color-default-100)',
            200: 'var(--color-default-200)',
            300: 'var(--color-default-300)',
            400: 'var(--color-default-400)',
            500: 'var(--color-default-500)',
            600: 'var(--color-default-600)',
            700: 'var(--color-default-700)',
            800: 'var(--color-default-800)',
            900: 'var(--color-default-900)',
            foreground: 'var(--color-default-foreground)',
            DEFAULT: 'var(--color-default)',
          },
          primary: {
            50: 'var(--color-primary-50)',
            100: 'var(--color-primary-100)',
            200: 'var(--color-primary-200)',
            300: 'var(--color-primary-300)',
            400: 'var(--color-primary-400)',
            500: 'var(--color-primary-500)',
            600: 'var(--color-primary-600)',
            700: 'var(--color-primary-700)',
            800: 'var(--color-primary-800)',
            900: 'var(--color-primary-900)',
            foreground: 'var(--color-primary-foreground)',
            DEFAULT: 'var(--color-primary)',
          },
          secondary: {
            50: 'var(--color-secondary-50)',
            100: 'var(--color-secondary-100)',
            200: 'var(--color-secondary-200)',
            300: 'var(--color-secondary-300)',
            400: 'var(--color-secondary-400)',
            500: 'var(--color-secondary-500)',
            600: 'var(--color-secondary-600)',
            700: 'var(--color-secondary-700)',
            800: 'var(--color-secondary-800)',
            900: 'var(--color-secondary-900)',
            foreground: 'var(--color-secondary-foreground)',
            DEFAULT: 'var(--color-secondary)',
          },
          success: {
            50: 'var(--color-success-50)',
            100: 'var(--color-success-100)',
            200: 'var(--color-success-200)',
            300: 'var(--color-success-300)',
            400: 'var(--color-success-400)',
            500: 'var(--color-success-500)',
            600: 'var(--color-success-600)',
            700: 'var(--color-success-700)',
            800: 'var(--color-success-800)',
            900: 'var(--color-success-900)',
            foreground: 'var(--color-success-foreground)',
            DEFAULT: 'var(--color-success)',
          },
          warning: {
            50: 'var(--color-warning-50)',
            100: 'var(--color-warning-100)',
            200: 'var(--color-warning-200)',
            300: 'var(--color-warning-300)',
            400: 'var(--color-warning-400)',
            500: 'var(--color-warning-500)',
            600: 'var(--color-warning-600)',
            700: 'var(--color-warning-700)',
            800: 'var(--color-warning-800)',
            900: 'var(--color-warning-900)',
            foreground: 'var(--color-warning-foreground)',
            DEFAULT: 'var(--color-warning)',
          },
          danger: {
            50: 'var(--color-danger-50)',
            100: 'var(--color-danger-100)',
            200: 'var(--color-danger-200)',
            300: 'var(--color-danger-300)',
            400: 'var(--color-danger-400)',
            500: 'var(--color-danger-500)',
            600: 'var(--color-danger-600)',
            700: 'var(--color-danger-700)',
            800: 'var(--color-danger-800)',
            900: 'var(--color-danger-900)',
            foreground: 'var(--color-danger-foreground)',
            DEFAULT: 'var(--color-danger)',
          },
          background: 'var(--color-background)',
          foreground: 'var(--color-foreground)',
          content1: {
            DEFAULT: 'var(--color-content1)',
            foreground: 'var(--color-content1-foreground)',
          },
          content2: {
            DEFAULT: 'var(--color-content2)',
            foreground: 'var(--color-content2-foreground)',
          },
          content3: {
            DEFAULT: 'var(--color-content3)',
            foreground: 'var(--color-content3-foreground)',
          },
          content4: {
            DEFAULT: 'var(--color-content4)',
            foreground: 'var(--color-content4-foreground)',
          },
          focus: 'var(--color-focus)',
          overlay: 'var(--color-overlay)',
        },
        opacity: {
          disabled: 'var(--disabled-opacity)',
        },
      },
    },
    darkMode: 'class', // Ermöglicht Theme-Wechsel mit der Klasse 'dark'
    plugins: [],
  }