// /** @type {import('tailwindcss').Config} */
// const { fontFamily } = require("tailwindcss/defaultTheme")

// module.exports = {
//   darkMode: ["class"],
//   content: [
//     "./src/app/**/*.{js,jsx,mdx}",
//     "./src/components/**/*.{js,jsx,mdx}",
//     "./src/pages/**/*.{js,jsx,mdx}",
//     "*.{js,ts,jsx,tsx,mdx}",
//   ],
//   theme: {
//     container: {
//       center: true,
//       padding: "2rem",
//       screens: {
//         "2xl": "1400px",
//       },
//     },
//     extend: {
//       colors: {
//         border: "hsl(var(--border))",
//         input: "hsl(var(--input))",
//         ring: "hsl(var(--ring))",
//         background: "hsl(var(--background))",
//         foreground: "hsl(var(--foreground))",
//         primary: {
//           DEFAULT: "hsl(var(--primary))",
//           foreground: "hsl(var(--primary-foreground))",
//         },
//         secondary: {
//           DEFAULT: "hsl(var(--secondary))",
//           foreground: "hsl(var(--secondary-foreground))",
//         },
//         destructive: {
//           DEFAULT: "hsl(var(--destructive))",
//           foreground: "hsl(var(--destructive-foreground))",
//         },
//         muted: {
//           DEFAULT: "hsl(var(--muted))",
//           foreground: "hsl(var(--muted-foreground))",
//         },
//         accent: {
//           DEFAULT: "hsl(var(--accent))",
//           foreground: "hsl(var(--accent-foreground))",
//         },
//         popover: {
//           DEFAULT: "hsl(var(--popover))",
//           foreground: "hsl(var(--popover-foreground))",
//         },
//         card: {
//           DEFAULT: "hsl(var(--card))",
//           foreground: "hsl(var(--card-foreground))",
//         },
//         background: "var(--color-background)",
//         foreground: "var(--color-foreground)",
//         primary: {
//           50: "var(--color-primary-50)",
//           100: "var(--color-primary-100)",
//           200: "var(--color-primary-200)",
//           300: "var(--color-primary-300)",
//           400: "var(--color-primary-400)",
//           500: "var(--color-primary-500)",
//           600: "var(--color-primary-600)",
//           700: "var(--color-primary-700)",
//           800: "var(--color-primary-800)",
//           900: "var(--color-primary-900)",
//           DEFAULT: "var(--color-primary-500)",
//           foreground: "var(--color-primary-foreground)",
//         },
//         secondary: {
//           50: "var(--color-secondary-50)",
//           100: "var(--color-secondary-100)",
//           200: "var(--color-secondary-200)",
//           300: "var(--color-secondary-300)",
//           400: "var(--color-secondary-400)",
//           500: "var(--color-secondary-500)",
//           600: "var(--color-secondary-600)",
//           700: "var(--color-secondary-700)",
//           800: "var(--color-secondary-800)",
//           900: "var(--color-secondary-900)",
//           DEFAULT: "var(--color-secondary-500)",
//           foreground: "var(--color-secondary-foreground)",
//         },
//         default: {
//           50: "var(--color-default-50)",
//           100: "var(--color-default-100)",
//           200: "var(--color-default-200)",
//           300: "var(--color-default-300)",
//           400: "var(--color-default-400)",
//           500: "var(--color-default-500)",
//           600: "var(--color-default-600)",
//           700: "var(--color-default-700)",
//           800: "var(--color-default-800)",
//           900: "var(--color-default-900)",
//           DEFAULT: "var(--color-default-500)",
//           foreground: "var(--color-default-foreground)",
//         },
//         success: {
//           50: "var(--color-success-50)",
//           100: "var(--color-success-100)",
//           200: "var(--color-success-200)",
//           300: "var(--color-success-300)",
//           400: "var(--color-success-400)",
//           500: "var(--color-success-500)",
//           600: "var(--color-success-600)",
//           700: "var(--color-success-700)",
//           800: "var(--color-success-800)",
//           900: "var(--color-success-900)",
//           DEFAULT: "var(--color-success-500)",
//           foreground: "var(--color-success-foreground)",
//         },
//         warning: {
//           50: "var(--color-warning-50)",
//           100: "var(--color-warning-100)",
//           200: "var(--color-warning-200)",
//           300: "var(--color-warning-300)",
//           400: "var(--color-warning-400)",
//           500: "var(--color-warning-500)",
//           600: "var(--color-warning-600)",
//           700: "var(--color-warning-700)",
//           800: "var(--color-warning-800)",
//           900: "var(--color-warning-900)",
//           DEFAULT: "var(--color-warning-500)",
//           foreground: "var(--color-warning-foreground)",
//         },
//         danger: {
//           50: "var(--color-danger-50)",
//           100: "var(--color-danger-100)",
//           200: "var(--color-danger-200)",
//           300: "var(--color-danger-300)",
//           400: "var(--color-danger-400)",
//           500: "var(--color-danger-500)",
//           600: "var(--color-danger-600)",
//           700: "var(--color-danger-700)",
//           800: "var(--color-danger-800)",
//           900: "var(--color-danger-900)",
//           DEFAULT: "var(--color-danger-500)",
//           foreground: "var(--color-danger-foreground)",
//         },
//         content1: {
//           DEFAULT: "var(--color-content1)",
//           foreground: "var(--color-content1-foreground)",
//         },
//         content2: {
//           DEFAULT: "var(--color-content2)",
//           foreground: "var(--color-content2-foreground)",
//         },
//         content3: {
//           DEFAULT: "var(--color-content3)",
//           foreground: "var(--color-content3-foreground)",
//         },
//         content4: {
//           DEFAULT: "var(--color-content4)",
//           foreground: "var(--color-content4-foreground)",
//         },
//       },
//       borderRadius: {
//         lg: "var(--radius)",
//         md: "calc(var(--radius) - 2px)",
//         sm: "calc(var(--radius) - 4px)",
//       },
//       fontFamily: {
//         sans: ["var(--font-sans)", ...fontFamily.sans],
//       },
//       keyframes: {
//         "accordion-down": {
//           from: { height: 0 },
//           to: { height: "var(--radix-accordion-content-height)" },
//         },
//         "accordion-up": {
//           from: { height: "var(--radix-accordion-content-height)" },
//           to: { height: 0 },
//         },
//       },
//       animation: {
//         "accordion-down": "accordion-down 0.2s ease-out",
//         "accordion-up": "accordion-up 0.2s ease-out",
//       },
//     },
//   },
//   //plugins: [require("tailwindcss-animate")], 
// }
